services:
  mysql:
    image: mysql:latest
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: transport_application
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "13306:3306" # เปลี่ยน Host Port เป็น 13306

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-boot-backend
    restart: always
    ports:
      - "18080:8080" # เปลี่ยน Host Port เป็น 18080
    volumes:
      - ./backend:/app
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://my-mysql:3306/transport_application?serverTimezone=Asia/Bangkok
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-frontend
    restart: always
    ports:
      - "15173:5173" # เปลี่ยน Host Port เป็น 15173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend

networks:
  472-deploy-g1:
    driver: bridge
