services:
  mysql:
    image: mysql:latest
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: transport_application
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "13306:3306" # เปลี่ยน Host Port เป็น 13306

  backend:
    image: nathanontp/spring-backend:latest
    container_name: spring-boot-backend
    restart: always
    ports:
      - "18080:8080" # เปลี่ยน Host Port เป็น 18080
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - STRIPE_TEST_KEY=${STRIPE_TEST_KEY}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_EMAIL_SENDER_HOST=${SPRING_EMAIL_SENDER_HOST}
      - PROFILE=${PROFILE}

  frontend:
    image: nathanontp/vue-frontend:latest
    container_name: vue-frontend
    restart: always
    ports:
      - "14173:4173"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}

networks:
  472-deploy-g1:
    driver: bridge
